#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Regenerate the compact manuscript/result figures directly from repository CSV/JSON files.

This script does not require the large HDF5 reconstruction cubes.

Generated figures:
- reconstruction SAM / PSNR / RMSE
- per-band RMSE
- per-band spatial correlation
- RGB-resolution ablation
- functional-validation R2 with fold standard deviations
- fold-wise delta R2

Observed-vs-predicted scatterplots require test_predictions.csv, which is
generated by scripts/07_restrans21_40band_5fold.py and intentionally is not
required for the compact repository summary.
"""

from pathlib import Path
import json

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
OUT = ROOT / "figures_generated"
OUT.mkdir(parents=True, exist_ok=True)

DPI = 600
FIGSIZE = (6.6, 4.6)


def save(stem):
    plt.tight_layout()
    plt.savefig(OUT / f"{stem}.png", dpi=DPI, bbox_inches="tight")
    plt.savefig(OUT / f"{stem}.pdf", bbox_inches="tight")
    plt.close()


def load_json(path):
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Main reconstruction comparison
# ---------------------------------------------------------------------------

rgb = load_json(
    RESULTS / "reconstruction" / "rgb_only_result.json"
)
rgb802 = load_json(
    RESULTS / "reconstruction" / "rgb_plus_802_result.json"
)

blocks = {
    "RGB only": rgb["official_checkpoint_diagnostic_full"],
    "RGB + 802 nm": rgb802["official_checkpoint_diagnostic_full"],
}

for metric, ylabel, stem in [
    ("SAM", "Spectral angle (degrees)", "reconstruction_SAM"),
    ("PSNR", "PSNR (dB)", "reconstruction_PSNR"),
    ("RMSE", "RMSE", "reconstruction_RMSE"),
]:
    labels = list(blocks)
    vals = [blocks[x][metric] for x in labels]

    plt.figure(figsize=FIGSIZE)
    bars = plt.bar(labels, vals)

    for b, v in zip(bars, vals):
        fmt = f"{v:.4f}" if metric == "RMSE" else f"{v:.3f}"
        plt.text(
            b.get_x() + b.get_width() / 2,
            b.get_height(),
            fmt,
            ha="center",
            va="bottom",
        )

    plt.ylabel(ylabel)
    save(stem)


# ---------------------------------------------------------------------------
# Per-wavelength reconstruction fidelity
# ---------------------------------------------------------------------------

pb = pd.read_csv(
    RESULTS
    / "per_band"
    / "per_wavelength_bgr_vs_bgr_plus_nir.csv"
)

w = pb["wavelength_nm"]

plt.figure(figsize=FIGSIZE)
plt.plot(
    w,
    pb["rmse_bgr_full"],
    marker="o",
    markersize=3,
    label="RGB only",
)
plt.plot(
    w,
    pb["rmse_bgr_plus_nir_full"],
    marker="s",
    markersize=3,
    label="RGB + 802 nm",
)
plt.axvline(700, linestyle="--", linewidth=1)
plt.axvline(802.32, linestyle=":", linewidth=1)
plt.xlabel("Wavelength (nm)")
plt.ylabel("RMSE")
plt.legend(frameon=False)
save("per_band_RMSE")

plt.figure(figsize=FIGSIZE)
plt.plot(
    w,
    pb["corr_bgr_full"],
    marker="o",
    markersize=3,
    label="RGB only",
)
plt.plot(
    w,
    pb["corr_bgr_plus_nir_full"],
    marker="s",
    markersize=3,
    label="RGB + 802 nm",
)
plt.axhline(0, linewidth=0.8)
plt.axvline(700, linestyle="--", linewidth=1)
plt.axvline(802.32, linestyle=":", linewidth=1)
plt.xlabel("Wavelength (nm)")
plt.ylabel("Spatial Pearson correlation")
plt.ylim(-0.2, 1.02)
plt.legend(frameon=False)
save("per_band_spatial_correlation")


# ---------------------------------------------------------------------------
# RGB-resolution ablation
# ---------------------------------------------------------------------------

x1 = rgb802["official_checkpoint_diagnostic_full"]
abl = [(1, 1000, x1["SAM"])]

for factor in [2, 4, 8]:
    r = load_json(
        RESULTS
        / "reconstruction"
        / f"rgb_resolution_x{factor}_result.json"
    )
    abl.append(
        (
            factor,
            int(r["rgb_native_resolution"][0]),
            r["official_checkpoint_diagnostic_full"]["SAM"],
        )
    )

abl = pd.DataFrame(
    abl,
    columns=["factor", "native_pixels", "SAM"],
)

plt.figure(figsize=FIGSIZE)
plt.plot(
    abl["factor"],
    abl["SAM"],
    marker="o",
)
for _, row in abl.iterrows():
    plt.text(
        row["factor"],
        row["SAM"],
        f" {int(row['native_pixels'])} px",
        va="bottom",
    )
plt.xticks([1, 2, 4, 8], ["×1", "×2", "×4", "×8"])
plt.xlabel("RGB downsampling factor")
plt.ylabel("SAM (degrees)")
save("RGB_resolution_ablation")


# ---------------------------------------------------------------------------
# Downstream model transfer
# ---------------------------------------------------------------------------

fm = pd.read_csv(
    RESULTS / "functional_validation" / "fold_metrics.csv"
)

source_order = ["genuine", "bgr_plus_802", "bgr_only"]
source_labels = {
    "genuine": "Genuine HSI",
    "bgr_plus_802": "RGB + 802 nm",
    "bgr_only": "RGB only",
}
targets = ["DM", "NC", "NU"]
target_labels = ["Dry matter", "N content", "N uptake"]

stats = (
    fm.groupby(["source", "target"])["R2"]
    .agg(["mean", "std"])
    .reset_index()
)

x = np.arange(len(targets), dtype=float)
width = 0.23

plt.figure(figsize=(7.2, 4.8))
for j, source in enumerate(source_order):
    sub = (
        stats[stats["source"] == source]
        .set_index("target")
        .reindex(targets)
    )

    xpos = x + (j - 1) * width
    plt.bar(
        xpos,
        sub["mean"].to_numpy(),
        width=width,
        yerr=sub["std"].to_numpy(),
        capsize=3,
        label=source_labels[source],
    )

plt.axhline(0, linewidth=0.8)
plt.xticks(x, target_labels)
plt.ylabel(r"$R^2$")
plt.legend(frameon=False)
save("functional-validation_R2")


pivot = fm.pivot_table(
    index=["fold", "target"],
    columns="source",
    values="R2",
).reset_index()

pivot["delta_bgr802"] = (
    pivot["bgr_plus_802"] - pivot["genuine"]
)
pivot["delta_bgr"] = (
    pivot["bgr_only"] - pivot["genuine"]
)

plt.figure(figsize=(7.2, 4.8))
offsets = np.linspace(-0.10, 0.10, 5)

for i, target in enumerate(targets):
    sub = pivot[pivot["target"] == target].sort_values("fold")

    y802 = sub["delta_bgr802"].to_numpy()
    yrgb = sub["delta_bgr"].to_numpy()

    plt.scatter(
        x[i] + offsets,
        y802,
        marker="o",
        label="RGB + 802 nm" if i == 0 else None,
    )
    plt.scatter(
        x[i] + offsets,
        yrgb,
        marker="x",
        label="RGB only" if i == 0 else None,
    )

    plt.scatter(
        [x[i]],
        [np.mean(y802)],
        s=90,
        marker="D",
    )
    plt.scatter(
        [x[i]],
        [np.mean(yrgb)],
        s=90,
        marker="P",
    )

plt.axhline(0, linewidth=0.9)
plt.xticks(x, target_labels)
plt.ylabel(r"$\Delta R^2$ (reconstructed − genuine)")
plt.legend(frameon=False)
save("foldwise_transfer_delta_R2")


print("Figures written to:")
print(OUT)
